--

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,6 +26,9 @@ jobs:
       - name: Build and pack
         run: dotnet pack ./src/file.handle.fast.support/FastSupport.File.csproj -c Release --output ./nupkg
 
+      - name: Remove existing GitHub source (if any)
+        run: dotnet nuget remove source github || echo "Source github not found"
+
       - name: Add GitHub Packages source
         run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
 
